### ISSUE TITLE
Video Not Found: Crash Course on Frontend Performance

### ISSUE THREAD

**Issue by thisizkp** [perf-rocks/perf.rocks#131]
In [Talks and Slides](http://perf.rocks/talks-and-slides/) category, the last 3rd from the list [Crash Course on Frontend Performance](http://www.devoxx.com/display/DV12/Faster+Websites++Crash+Course+on+Frontend+Performance) videos & slides link are not found.

**Comment by ThisIzKp** [comment]
I found the links for the new videos but in two parts, I don't think the template right now supports the option of adding two video links. 

I would like to suggest a feature of adding multiple links and also custom text for the links. Like `video-1` and `video-2`. 

@danielguillan let me know how do you think we should approach this. I'll send the PR

**Comment by danielguillan** [comment]
Hey @ThisIzKp, thanks for catching that!

I'm in the process of rebuilding perf.rocks from the ground up, and so for the time being I will only update its content.

In the meantime I'd suggest having two entries, one for each part of the video.

**Comment by ThisIzKp** [comment]
@danielguillan cool. Should I work on it, the template having multiple options of adding video links?

**Comment by danielguillan** [comment]
Nope, I don't want to do any updates to the current site. But I would appreciate a PR that splits the entry in `/data/videos.yml` into two separate videos, one for each part.

**Comment by ThisIzKp** [comment]
sure, will check that
